apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pizza-menu.fullname" . }}
  labels:
{{ include "pizza-menu.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pizza-menu.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pizza-menu.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      
      containers:
      
        - name: {{ .Chart.Name }}
          env: 
            - name: SPRING_APPLICATION_NAME
              value: {{ include "pizza-menu.name" . }}
            - name: JAEGER_SERVICE_NAME
              value: {{ include "pizza-menu.fullname" . }}
            - name: OPENTRACING_JAEGER_UDPSENDER_HOST
              value: jaeger-simplest-agent.default
            - name: LOGGING_LEVEL_ROOT
              value: INFO
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
