apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pizza-menu.name" . }}-servicemonitor
  namespace: monitoring
  labels:
      release: monitoring
spec:
  endpoints:
    - interval: 10s
      path: /metrics
      targetPort: http      
  namespaceSelector:
    matchNames:
      - "{{.Release.Namespace}}"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pizza-menu.name" . }}
      