{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
        {{- with .Values.ingress.annotations }}
  annotations:
        {{- toYaml . | nindent 4 }}
        {{- end }}

  labels:
{{ include "pizza-menu.labels" . | indent 4 }}
  name: {{ include "pizza-menu.name" . }}-ingress
spec:
  backend:
    serviceName: {{ include "pizza-menu.name" . }}-frontend
    servicePort: 8080
  rules:
    - http:
        paths:
          - backend:
              serviceName: {{ include "pizza-menu.name" . }}-facade
              servicePort: 8080
            path: /graphql
{{- end }}

