apiVersion: v1
kind: Service
metadata:
  name: {{ include "pizza-menu.name" . }}-facade
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "pizza-menu.name" . }}-facade
    app.kubernetes.io/instance: {{ include "pizza-menu.name" . }}
