apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "pizza-menu.name" . }}-frontend
    labels:
{{ include "pizza-menu.labels" . | indent 8 }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ include "pizza-menu.name" . }}-frontend
            app.kubernetes.io/instance: {{ include "pizza-menu.name" . }}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ include "pizza-menu.name" . }}-frontend
                app.kubernetes.io/instance: {{ include "pizza-menu.name" . }}
        spec:
                {{- with .Values.imagePullSecrets }}
            imagePullSecrets:
                {{- toYaml . | nindent 16 }}
                {{- end }}
            containers:
                - name: {{ .Chart.Name }}
                  env:
                      - name: VUE_APP_PIZZA_API
                        value: "/graphql"
                  image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
                  imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
                  ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
                  resources: {}
                {{- with .Values.nodeSelector  }}
            nodeSelector:

                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.affinity }}
            affinity:
                {{- toYaml . | nindent 16 }}
                {{- end }}
                {{- with .Values.tolerations }}
            tolerations:
            {{- toYaml . | nindent 16 }}
        {{- end }}