apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-facade
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-facade
    app.kubernetes.io/instance: {{ .Release.Name }}
