apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pizza-menu.name" . }}-name-creator
  labels:
{{ include "pizza-menu.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pizza-menu.name" . }}-name-creator
      app.kubernetes.io/instance: {{ include "pizza-menu.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pizza-menu.name" . }}-name-creator
        app.kubernetes.io/instance: {{ include "pizza-menu.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      
      containers:
      
        - name: {{ .Chart.Name }}
          env: 
            - name: QUARKUS_HTTP_PORT
              value: {{ .Values.service.port | quote}}
            - name: QUARKUS_LOG_LEVEL
              value: INFO
            - name: QUARKUS_JAEGER_ENDPOINT
              value: "http://jaeger-collector.jaeger.svc:14268/api/traces"
          image: "{{ .Values.name.image.repository }}:{{ .Values.name.image.tag }}"
          imagePullPolicy: {{ .Values.name.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
