apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pizza-menu.name" . }}-facade
  labels:
{{ include "pizza-menu.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pizza-menu.name" . }}-facade
      app.kubernetes.io/instance: {{ include "pizza-menu.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pizza-menu.name" . }}-facade
        app.kubernetes.io/instance: {{ include "pizza-menu.name" . }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      
      containers:
        - name: {{ .Chart.Name }}
          env: 
            - name: PIZZA_NAME_ENDPOINT
              value: "http://{{ include "pizza-menu.name" . }}-name-creator.{{ .Release.Namespace }}.svc:8080"
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote}}
            - name: SPRING_APPLICATION_NAME
              value: {{ include "pizza-menu.name" . }}-facade
            - name: LOGGING_LEVEL_ROOT
              value: INFO
          image: "{{ .Values.facade.image.repository }}:{{ .Values.facade.image.tag }}"
          imagePullPolicy: {{ .Values.facade.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
