version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of the first service
    image: docker.io/gabrielsson/pizza-menu-frontend:3.0.0
    ports:
      - "8080:8080"

  backend:
    image: docker.io/gabrielsson/pizza-menu-facade:3.0.0-JVM
    restart: always
    environment:
      PIZZA_NAME_ENDPOINT: http://cities:8082
      QUARKUS_LOG_LEVEL: INFO
    ports:
      - "8082:8080"
    #mem_limit: 60m
    

  cities:
    image: docker.io/gabrielsson/pizza-name-creator:3.0.0-JVM
    restart: always
    environment:
      QUARKUS_LOG_LEVEL: INFO
    #mem_limit: 60m

