# Default values for pizza-menu.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

frontend:
  image:
    repository: gabrielsson/pizza-menu-frontend
    tag: 2.0.0
    pullPolicy: Always

facade:
  image:
    repository: gabrielsson/pizza-menu-facade
    tag: 2.0.0
    pullPolicy: Always

name:
  image:
    repository: gabrielsson/pizza-name-creator
    tag: 2.0.1
    pullPolicy: Always

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
